Label
ezraermy/Ruby-Group-Capstone pull request #37
Opened 2023-06-06 22:01 UTC by Swarzstein

## In this pull request:
- Create a Book class in a separate .rb file.
- Create a Label class with an association to the Item class (in a separate .rb file).
- All Book class properties visible in the diagram should be defined and set up in the constructor method.
- All Label class properties visible in the diagram should be defined and set up in the constructor method.
- Implement methods:
  - add_item method in the Label class
    - should take an instance of the Item class as an input
    - should add the input item to the collection of items
    - should add self as a property of the item object (by using the correct setter from the item object)
  - can_be_archived?() in the Book class
    - should override the method from the parent class
    - should return true if parent's method returns true OR if cover_state equals to "bad"
    - otherwise, it should return false
- Add unit tests for all implemented methods.

2023-06-06 22:37 UTC, ezraermy approved these changes
# STATUS: APPROVED 🟢
## Hi @Swarzstein , 
![Congratulations!GIF](https://user-images.githubusercontent.com/55918904/191301390-43d62dfa-bfdc-49c5-943b-4d72f4ea5bb8.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- You used GitHub flow correctly. ✔
- Descriptive pull request. ✔

## Optional suggestions

Please consider the following changes below!👏👏👏

Add missing require statements in 'label_spec.rb': Ensure that all required dependencies are properly imported. In this case, you need to include require 'date' to use the Date class.

2023-06-07 00:06 UTC, Muhammad0602 approved these changes
> ## Status: Approved ✔️
## Hi @Swarzstein 
> 
>Your project looks great; you have done it exceptionally well. 
> 
> ### Congratulations! 🎉 🎉 🎉 🎉
>
![ThumbsUpOkayGIF](https://github.com/ezraermy/Ruby-Group-Capstone/assets/113791476/81e8b4b0-dbef-4d6e-a600-dabf9b0b07ed)

 
> 
> You may close this Pull Request and merge the changes Keep being awesome devs and good luck with your next milestone!
> 
> ### To Highlight
> ✅ Descriptive pull request message
   ✅ linter error checks validated 
   ✅ Documented your work professionally 
> 
> ### Optional suggestions
> Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

> Cheers and Happy coding! 👏 👏 👏

2023-06-07 00:07 UTC, Muhammad0602 commented
I think we should discuss the item.rb together and decide how it should look.

2023-06-07 09:46 UTC, Muhammad0602 requested changes

2023-06-07 09:46 UTC, Muhammad0602 commented on classes/label.rb
> +  end
As it is stated in the requirements `should add self as a property of the item object (by using the correct setter from the item object)` you should add self as a property in your add_item method.

2023-06-07 16:48 UTC, merged